project:
  type: website

website:
  title: "DETECT R33 Dashboards"
  navbar:
    search: true
    logo: graphics/detect_logo.png
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Dashboards"
        menu:
          - sections/recruitment_and_scheduling_tracker.qmd
          - sections/clinician_screening_completion_tracker.qmd
          - sections/detect_tool_pilot_dashboard.qmd


format:
  html:
    page-layout: full
    theme: 
    - cosmo
    - assets/custom_style.css # custom formatting for value boxes
    css: assets/custom_style.css # custom formatting for value boxes
    toc: true


# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quartoâ€™s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto

